### ISSUE TITLE
What is minimum size of the textfield should be ? 

### ISSUE THREAD

**Issue by Premal-Khetani** [AzimoLabs/SMFloatingLabelTextField#1]
Hello, 

First of all this is really very good library for floating Labels upon the textfields. i want to know that what is the minimum size for the textfield? and what about if we want to apply this feature to textView also as there are some fields which contains "\n" also. 

Thank you.

**Comment by Moskacz** [comment]
Hi Premal-Khetani,

hope you're well. I don't know if I understand you question properly, but there is no minimum size of textfield requirement. The floating label is another view attached to the textfield using constraints. The label will be displayed even if textfield has zero height or width, unless you set `clipsToBounds` flat to `YES`. 

This library doesn't support UITextView class.

**Comment by Premal-Khetani** [comment]
@Moskacz  Sorry for the late reply. Well Thanks for the information but i want to know the minimum frame size of the fields. so according to them i can design them in storyboards.

Thanks

**Comment by matkuznik** [comment]
Hi, sorry for late response. Like @Moskacz said, ` there is no minimum size of textfield requirement`. This is just subclass of`UITextField` so you should treat it as `UITextField`. We do not add any constraints for it size.
