### ISSUE TITLE
Setting the attributedPlaceholder not working 

### ISSUE THREAD

**Issue by BuntyM** [AzimoLabs/SMFloatingLabelTextField#4]
First of all, its really nice to see. 
Really appreciate.

i have faced this issues, if we set `attributedPlaceholder` in that case label does't come up so we have to use `placeholder` only or is there any alternate.

Thanks

**Comment by Moskacz** [comment]
@BuntyM we pushed new version (0.3.0) please check if it works. Please note that you need to control color of floating label by properties 
```
@property (nonatomic, strong, nonnull) IBInspectable UIColor *floatingLabelActiveColor;
@property (nonatomic, strong, nonnull) IBInspectable UIColor *floatingLabelPassiveColor;
```
even if you set attributed placeholder of text field.

**Comment by matkuznik** [comment]
@BuntyM we updated pod to version 0.3.1. It include small appearance improvement. Now `floatingLabelFont` will be forced to floating label.

**Comment by BuntyM** [comment]
@matkuznik thanks a lot. i also did few changes for achieving the same, but yeah for sure i going to pull latest changes. really appreciate.
